"""fase 2.1 campos aluno + acesso detalhes

Revision ID: 8c81436e0086
Revises: f2d9f6545bb8
Create Date: 2026-09-11 20:45:35.689346

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8c81436e0086"
down_revision: str | Sequence[str] | None = "f2d9f6545bb8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("acesso_logs", sa.Column("detalhes", sa.Text(), nullable=True))
    op.add_column("alunos", sa.Column("data_nasc", sa.Date(), nullable=True))
    op.add_column("alunos", sa.Column("observacoes", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("alunos", "observacoes")
    op.drop_column("alunos", "data_nasc")
    op.drop_column("acesso_logs", "detalhes")
    # ### end Alembic commands ###
