"""fase_4_13_foto_aluno_funcionario

Revision ID: 6f1b91800ae0
Revises: 5934a9e19afa
Create Date: 2026-09-13 15:17:46.882608

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f1b91800ae0"
down_revision: str | Sequence[str] | None = "5934a9e19afa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("alunos", sa.Column("foto", sa.String(length=255), nullable=True))
    op.add_column("funcionarios", sa.Column("foto", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("funcionarios", "foto")
    op.drop_column("alunos", "foto")
    # ### end Alembic commands ###
