"""fase_4_13_senha_plain_funcionario

Revision ID: ef0330e40ade
Revises: 6f1b91800ae0
Create Date: 2026-09-14 00:33:03.786374

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ef0330e40ade'
down_revision: str | Sequence[str] | None = '6f1b91800ae0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funcionarios', sa.Column('senha', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funcionarios', 'senha')
    # ### end Alembic commands ###
