"""initial gymflux v1

Revision ID: f2d9f6545bb8
Revises:
Create Date: 2026-09-11 20:32:21.988448

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f2d9f6545bb8"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alunos",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("nome", sa.String(length=120), nullable=False),
        sa.Column("cpf", sa.String(length=14), nullable=True),
        sa.Column("telefone", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=120), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("bloqueado_manual", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alunos_cpf"), "alunos", ["cpf"], unique=True)
    op.create_table(
        "planos",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("nome", sa.String(length=80), nullable=False),
        sa.Column("duracao_dias", sa.Integer(), nullable=False),
        sa.Column("valor", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("tolerancia_dias", sa.Integer(), nullable=False),
        sa.Column("tipo", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "acesso_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("aluno_id", sa.String(length=36), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("direcao", sa.String(length=10), nullable=False),
        sa.Column("resultado", sa.String(length=20), nullable=False),
        sa.Column("motivo", sa.String(length=40), nullable=True),
        sa.Column("catraca_id", sa.String(length=36), nullable=True),
        sa.Column("timeout", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["aluno_id"], ["alunos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_acesso_logs_aluno_id"), "acesso_logs", ["aluno_id"], unique=False)
    op.create_index(op.f("ix_acesso_logs_timestamp"), "acesso_logs", ["timestamp"], unique=False)
    op.create_table(
        "matriculas",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("aluno_id", sa.String(length=36), nullable=False),
        sa.Column("plano_id", sa.String(length=36), nullable=False),
        sa.Column("inicio", sa.Date(), nullable=False),
        sa.Column("fim", sa.Date(), nullable=False),
        sa.Column("ativa", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["aluno_id"], ["alunos.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["plano_id"], ["planos.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_matriculas_aluno_ativa", "matriculas", ["aluno_id", "ativa"], unique=False)
    op.create_table(
        "pagamentos",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("aluno_id", sa.String(length=36), nullable=False),
        sa.Column("valor", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("vencimento", sa.Date(), nullable=False),
        sa.Column("pagamento", sa.Date(), nullable=True),
        sa.Column("forma", sa.String(length=20), nullable=True),
        sa.Column("competencia", sa.String(length=7), nullable=True),
        sa.ForeignKeyConstraint(["aluno_id"], ["alunos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pagamentos_aluno_id"), "pagamentos", ["aluno_id"], unique=False)
    op.create_index(op.f("ix_pagamentos_vencimento"), "pagamentos", ["vencimento"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pagamentos_vencimento"), table_name="pagamentos")
    op.drop_index(op.f("ix_pagamentos_aluno_id"), table_name="pagamentos")
    op.drop_table("pagamentos")
    op.drop_index("ix_matriculas_aluno_ativa", table_name="matriculas")
    op.drop_table("matriculas")
    op.drop_index(op.f("ix_acesso_logs_timestamp"), table_name="acesso_logs")
    op.drop_index(op.f("ix_acesso_logs_aluno_id"), table_name="acesso_logs")
    op.drop_table("acesso_logs")
    op.drop_table("planos")
    op.drop_index(op.f("ix_alunos_cpf"), table_name="alunos")
    op.drop_table("alunos")
    # ### end Alembic commands ###
